# quiz_data.py

QUIZ_QUESTOES = [
    # Agentes e Habilidades
    {"pergunta": "Qual agente possui a habilidade 'Orbes de Barreira' (parede de gelo)?", "opcoes": ["Sage", "Omen", "Cypher", "Killjoy"], "resposta": 0},
    {"pergunta": "Qual agente é originário do Brasil?", "opcoes": ["Raze", "Fade", "KAY/O", "Breach"], "resposta": 0},
    {"pergunta": "Quantos pontos de ultimate são necessários para carregar a habilidade da Jett?", "opcoes": ["6", "7", "8", "5"], "resposta": 0},
    {"pergunta": "Qual agente utiliza a habilidade 'Flecha Rastreadora'?", "opcoes": ["Cypher", "Sova", "Fade", "Skye"], "resposta": 1},
    {"pergunta": "Qual agente tem a habilidade de se transformar em uma poça de sombras e teleportar?", "opcoes": ["Reyna", "Omen", "Viper", "Astra"], "resposta": 1},
    {"pergunta": "Qual agente é um radiante focado em venenos e ácido?", "opcoes": ["Viper", "Killjoy", "Deadlock", "Sage"], "resposta": 0},
    {"pergunta": "Qual agente possui a habilidade 'Nuvem de Estilhaços' e granadas incendiárias baseadas em fogo?", "opcoes": ["Brimstone", "Phoenix", "Breach", "Sova"], "resposta": 1},
    {"pergunta": "Qual agente controlador manipula as estrelas no mapa cósmico?", "opcoes": ["Omen", "Viper", "Astra", "Brimstone"], "resposta": 2},
    {"pergunta": "Qual agente iniciador usa robôs e sinalizadores de flash baseados em luz solar?", "opcoes": ["Skye", "KAY/O", "Breach", "Fade"], "resposta": 0},
    {"pergunta": "Qual agente robótico foi construído para combater radiantes na guerra anterior?", "opcoes": ["Killjoy", "KAY/O", "Cypher", "Omen"], "resposta": 1},
    {"pergunta": "Qual agente duelista suga a vida dos inimigos abatidos para curar a si mesma?", "opcoes": ["Jett", "Raze", "Reyna", "Neon"], "resposta": 2},
    {"pergunta": "Qual agente sentinela usa armadilhas de contenção e fios trampa?", "opcoes": ["Sage", "Cypher", "Killjoy", "Chamber"], "resposta": 1},
    {"pergunta": "Qual agente iniciador utiliza ondas de choque sísmico para atordoar inimigos através de paredes?", "opcoes": ["Sova", "Breach", "Fade", "Skye"], "resposta": 1},
    {"pergunta": "Qual agente possui uma habilidade chamada 'Orbe de Lentidão'?", "opcoes": ["Sage", "Reyna", "Viper", "Omen"], "resposta": 0},
    {"pergunta": "Qual é a classe do agente Cypher?", "opcoes": ["Duelista", "Controlador", "Iniciador", "Sentinela"], "resposta": 3},
    {"pergunta": "Qual é a classe do agente Sova?", "opcoes": ["Duelista", "Controlador", "Iniciador", "Sentinela"], "resposta": 2},
    {"pergunta": "Qual agente é conhecido por correr em alta velocidade e gerar poças de eletricidade estática?", "opcoes": ["Jett", "Neon", "Raze", "Reyna"], "resposta": 1},
    {"pergunta": "Qual agente usa o feitiço de ressurreição em aliados caídos?", "opcoes": ["Sage", "Skye", "Reyna", "Deadlock"], "resposta": 0},
    {"pergunta": "Qual agente é um radiante com poderes baseados em nanotecnologia alemã?", "opcoes": ["Killjoy", "Brimstone", "Viper", "Cypher"], "resposta": 0},
    {"pergunta": "Qual agente francês possui armas customizadas de ouro e teleporte por estacas?", "opcoes": ["Cypher", "Chamber", "Deadlock", "Fade"], "resposta": 1},

    # Economia e Armas
    {"pergunta": "Qual é o custo padrão da Vandal no jogo?", "opcoes": ["2700", "2900", "3100", "2050"], "resposta": 1},
    {"pergunta": "Qual o custo padrão da Phantom no jogo?", "opcoes": ["2700", "2900", "3100", "2500"], "resposta": 1},
    {"pergunta": "Qual o nome da arma secundária (pistola) que custa 800 créditos e dispara tiros em rajada de três?", "opcoes": ["Classic", "Shorty", "Frenzy", "Ghost"], "resposta": 2},
    {"pergunta": "Qual é a arma de fogo pesada com maior taxa de tiro sustentada do jogo?", "opcoes": ["Ares", "Odin", "Bulldog", "Marshal"], "resposta": 1},
    {"pergunta": "Qual o nome da faca padrão (default) de melee do jogo?", "opcoes": ["Tactical Knife", "Kingdom Knife", "Melee Default", "Knife"], "resposta": 3},
    {"pergunta": "Qual a arma de precisão (sniper) de alto custo que elimina qualquer inimigo com um tiro no corpo ou cabeça?", "opcoes": ["Marshal", "Operator", "Sheriff", "Guardian"], "resposta": 1},
    {"pergunta": "Qual o limite máximo de créditos que um jogador pode acumular na conta?", "opcoes": ["9000", "10000", "12000", "8000"], "resposta": 0},
    {"pergunta": "Qual arma de fogo intermediária custa 1100 créditos e possui alta precisão à distância?", "opcoes": ["Stinger", "Spectre", "Bulldog", "Marshal"], "resposta": 3},
    {"pergunta": "Quanto custa a pistola Sheriff no jogo?", "opcoes": ["700", "800", "600", "500"], "resposta": 1},
    {"pergunta": "Qual o custo da submetralhadora Spectre?", "opcoes": ["1600", "1500", "1100", "2000"], "resposta": 0},
    {"pergunta": "Quantos créditos custa a arma Bulldog?", "opcoes": ["2050", "2100", "2900", "1500"], "resposta": 0},
    {"pergunta": "Qual pistola do jogo é uma escopeta de cano duplo de baixo custo?", "opcoes": ["Classic", "Shorty", "Frenzy", "Ghost"], "resposta": 1},
    {"pergunta": "Qual a escopeta automática de maior custo no jogo?", "opcoes": ["Bucky", "Judge", "Operator", "Ares"], "resposta": 1},
    {"pergunta": "Qual a escopeta de ação de bombeamento mais barata?", "opcoes": ["Judge", "Bucky", "Shorty", "Stinger"], "resposta": 1},
    {"pergunta": "Quantos créditos custa o escudo leve (armor)?", "opcoes": ["400", "500", "1000", "300"], "resposta": 0},
    {"pergunta": "Quantos créditos custa o escudo pesado (heavy armor)?", "opcoes": ["1000", "800", "600", "400"], "resposta": 1},
    {"pergunta": "Quantos pontos de vida e escudo somados o jogador possui com o escudo pesado?", "opcoes": ["125", "150", "200", "100"], "resposta": 1},
    {"pergunta": "Quantos pontos de vida e escudo o jogador possui com o escudo leve?", "opcoes": ["125", "150", "100", "175"], "resposta": 0},
    {"pergunta": "Qual arma possui um zoom tático de duas fases e mira laser integrada ao disparar?", "opcoes": ["Vandal", "Guardian", "Phantom", "Bulldog"], "resposta": 1},
    {"pergunta": "Qual arma secundária silenciada custa 500 créditos?", "opcoes": ["Classic", "Ghost", "Sheriff", "Shorty"], "resposta": 1},

    # Mapas e Mecânicas
    {"pergunta": "Qual mapa possui três bombsites (A, B e C)?", "opcoes": ["Ascent", "Bind", "Haven", "Split"], "resposta": 2},
    {"pergunta": "Qual mapa se passa em Veneza, Itália?", "opcoes": ["Bind", "Ascent", "Split", "Icebox"], "resposta": 1},
    {"pergunta": "Quantos segundos dura a rodada padrão (fase de compra + combate) em modo competitivo?", "opcoes": ["1 minuto e 40 segundos", "1 minuto e 50 segundos", "2 minutos", "1 minuto e 30 segundos"], "resposta": 0},
    {"pergunta": "Qual mapa possui cordas verticais e tirolesas mecânicas no centro do B?", "opcoes": ["Icebox", "Split", "Ascent", "Breeze"], "resposta": 0},
    {"pergunta": "Qual o nome do mapa localizado em um deserto com portais de teletransporte unidirecionais?", "opcoes": ["Bind", "Haven", "Lotus", "Sunset"], "resposta": 0},
    {"pergunta": "Qual o nome do mapa inspirado na cidade de Los Angeles?", "opcoes": ["Sunset", "Ascent", "Pearl", "Fracture"], "resposta": 0},
    {"pergunta": "Qual o nome do mapa subaquático localizado sob o domo?", "opcoes": ["Breeze", "Pearl", "Lotus", "Icebox"], "resposta": 1},
    {"pergunta": "Qual mapa apresenta portas giratórias mecânicas no centro?", "opcoes": ["Lotus", "Ascent", "Bind", "Pearl"], "resposta": 0},
    {"pergunta": "Qual mapa possui uma tirolesa central que atravessa todo o laboratório ligando o lado A ao B?", "opcoes": ["Fracture", "Icebox", "Breeze", "Split"], "resposta": 0},
    {"pergunta": "Qual mapa aberto se passa em uma instalação tropical com praias e ruínas?", "opcoes": ["Breeze", "Pearl", "Ascent", "Bind"], "resposta": 0},
    {"pergunta": "Quantas rodadas são necessárias para vencer uma partida competitiva normal no Valorant (sem prorrogação)?", "opcoes": ["13", "16", "10", "8"], "resposta": 0},
    {"pergunta": "Como se chama a fase de troca de lados na oitava rodada?", "opcoes": ["Troca de Lado / Half-Time", "Prorrogação", "Overtime", "Match Point"], "resposta": 0},
    {"pergunta": "Qual o nome dado quando um time vence 13 rodadas seguidas sem deixar o adversário pontuar?", "opcoes": ["Flawless", "Ace", "Atropelo / 13 a 0", "Thrifty"], "resposta": 2},
    {"pergunta": "O que significa a sigla 'Ace' durante uma rodada?", "opcoes": ["Eliminar todos os 5 membros do time inimigo sozinho", "Desarmar a Spike a tempo", "Morrer sem abates", "Comprar arma no pistol round"], "resposta": 0},
    {"pergunta": "O que significa o termo 'Flawless' ao final de uma rodada?", "opcoes": ["Nenhum membro do seu time morreu", "A Spike explodiu", "O time inimigo desistiu", "Você acertou apenas tiros na cabeça"], "resposta": 0},
    {"pergunta": "O que significa o termo 'Thrifty' no placar da rodada?", "opcoes": ["Vencer a rodada gastando muito pouco dinheiro contra um time equipado", "Morrer para a própria granada", "Comprar uma Vandal no 2º round", "Desarmar a Spike com 1 segundo restante"], "resposta": 0},
    {"pergunta": "Quanto tempo leva para plantar a Spike no chão?", "opcoes": ["2 segundos", "4 segundos", "5 segundos", "3 segundos"], "resposta": 1},
    {"pergunta": "Quanto tempo leva para desarmar a Spike completamente?", "opcoes": ["7 segundos", "5 segundos", "10 segundos", "4 segundos"], "resposta": 0},
    {"pergunta": "Se o desarme da Spike for cortado pela metade, o progresso é salvo até qual marca?", "opcoes": ["Até os 3.5 segundos (metade)", "Não existe salvamento", "Até os 5 segundos", "Até o final"], "resposta": 0},
    {"pergunta": "Quanto tempo a Spike demora para explodir após ser plantada?", "opcoes": ["30 segundos", "45 segundos", "60 segundos", "25 segundos"], "resposta": 1},

    # Lore e Universo
    {"pergunta": "Qual o nome do laboratório onde a Radianita é estudada na lore do Reino?", "opcoes": ["Kingdom Corporation", "Radianite Core", "Omega Sector", "Alpha Facility"], "resposta": 0},
    {"pergunta": "Qual é o nome da entidade misteriosa que causou a Primeira Luz?", "opcoes": ["O Reino", "A Anomalia", "O Primórdio", "Desconhecido / First Light"], "resposta": 3},
    {"pergunta": "Qual o nome do planeta Terra na realidade alternativa espelhada do Valorant?", "opcoes": ["Terra Omega", "Terra Nova", "Mundo Espelho", "Dimensão X"], "resposta": 0},
    {"pergunta": "Qual organização secreta global opera e gerencia os Agentes do Protocolo?", "opcoes": ["Valorant Protocol", "Kingdom", "Aegis", "Radianite Task Force"], "resposta": 0},
    {"pergunta": "Qual agente é o líder tático e fundador oficial do Protocolo Valorant?", "opcoes": ["Brimstone", "Viper", "Cypher", "Sova"], "resposta": 0},
    {"pergunta": "De acordo com a lore, qual agente foi o primeiro a se juntar a Brimstone para formar o Protocolo?", "opcoes": ["Viper", "Sage", "Omen", "Jett"], "resposta": 0},
    {"pergunta": "Qual agente possui um artefato misterioso em seu corpo chamado de 'Núcleo Radianita' ou similar que lhe concede asas de energia?", "opcoes": ["Jett", "Reyna", "Sage", "Fade"], "resposta": 0},
    {"pergunta": "Qual agente tem um passado ligado à organização Alpha e Omega trabalhando como cientista antes da catástrofe?", "opcoes": ["Viper", "Killjoy", "Chamber", "Omen"], "resposta": 0},
    {"pergunta": "Qual agente guarda segredos e informações confidenciais sobre todos os outros membros do Protocolo em seu escritório?", "opcoes": ["Cypher", "Sova", "KAY/O", "Brimstone"], "resposta": 0},
    {"pergunta": "O que é a Radianita no universo de Valorant?", "opcoes": ["Uma fonte de energia misteriosa descoberta após a Primeira Luz", "Um tipo de arma extraterrestre", "Uma doença letal", "Um metal usado apenas para construção de facas"], "resposta": 0},

    # Perguntas Adicionais para passar de 150
    {"pergunta": "Qual desenvolvedora criou e mantém o jogo Valorant?", "opcoes": ["Riot Games", "Valve", "Epic Games", "Ubisoft"], "resposta": 0},
    {"pergunta": "Em que ano Valorant foi lançado oficialmente para PC?", "opcoes": ["2020", "2019", "2021", "2018"], "resposta": 0},
    {"pergunta": "Qual o nome do anticheat proprietário obrigatório para jogar Valorant no PC?", "opcoes": ["Vanguard", "Easy Anti-Cheat", "BattlEye", "Vac Net"], "resposta": 0},
    {"pergunta": "Qual o elo mais alto tradicional do competitivo de Valorant antes do Radiante?", "opcoes": ["Imortal", "Imortal 3", "Diamante", "Ascendente"], "resposta": 0},
    {"pergunta": "Qual tier de ranque foi introduzido entre Diamante e Imortal em atualizações passadas?", "opcoes": ["Ascendente", "Mestre", "Grandmaster", "Platina Elite"], "resposta": 0},
    {"pergunta": "Quantos jogadores compõem uma equipe em partidas competitivas normais de Valorant?", "opcoes": ["5", "3", "6", "4"], "resposta": 0},
    {"pergunta": "Qual o nome do modo de jogo rápido onde todos recebem a mesma arma aleatória que evolui a cada abate?", "opcoes": ["Disputa de Elmo / Escalation", "Pistol Round", "Mata-Mata", "Spike Rush"], "resposta": 0},
    {"pergunta": "Qual o nome do modo rápido onde todos os jogadores carregam uma Spike amplificada e duram poucos minutos por partida?", "opcoes": ["Spike Rush", "Disputa", "Personalizado", "Competitivo"], "resposta": 0},
    {"pergunta": "Qual o nome do modo onde os jogadores compram armas e lutam individualmente sem equipes em um mapa fechado?", "opcoes": ["Mata-Mata (Deathmatch)", "Batalha Naval", "Frenesi", "Prática"], "resposta": 0},
    {"pergunta": "Qual o nome da interface de mira customizada no jogo?", "opcoes": ["Crosshair", "Reticle", "Aim Sight", "Scope"], "resposta": 0},
    {"pergunta": "Qual a taxa de atualização de servidores (tickrate) padrão implementada pela Riot para o competitivo de Valorant?", "opcoes": ["128-tick", "64-tick", "30-tick", "256-tick"], "resposta": 0},
    {"pergunta": "Como se chama o torneio mundial oficial de e-sports de Valorant?", "opcoes": ["VCT (Valorant Champions Tour)", "The International", "Major", "Worlds"], "resposta": 0},
    {"pergunta": "Qual o nome do evento final de encerramento da temporada competitiva de Valorant?", "opcoes": ["Champions", "Masters", "Kickoff", "Challengers"], "resposta": 0},
    {"pergunta": "Qual time brasileiro de e-sports venceu o VCT Champions em 2022?", "opcoes": ["LOUD", "KRÜ Esports", "Furia", "MIBR"], "resposta": 0},
    {"pergunta": "Qual agente brasileiro ficou imortalizado com referências e bordões no lançamento do jogo?", "opcoes": ["Raze", "Fade", "Neon", "Brimstone"], "resposta": 0},
    {"pergunta": "Qual agente possui uma habilidade de flash chamada 'Clutch' ou 'Cegueira' em forma de clarão esférico?", "opcoes": ["Phoenix", "Reyna", "Yoru", "Todos os anteriores possuem flashes"], "resposta": 3},
    {"pergunta": "Qual o nome do clone falso que o agente Yoru pode enviar para enganar os inimigos?", "opcoes": ["Falsificação / Fakeout", "Sombra", "Clone", "Espelho"], "resposta": 0},
    {"pergunta": "Qual agente usa portais dimensionais para se infiltrar nas costas do inimigo com sua ultimate?", "opcoes": ["Yoru", "Omen", "Jett", "Reyna"], "resposta": 0},
    {"pergunta": "Qual o nome da armadilha de contenção de arame que congela os inimigos criada pela agente Deadlock?", "opcoes": ["Rede de Gravitúnel", "Sensor Sônico", "Barreira de Nanofios", "Aprisionamento"], "resposta": 1},
    {"pergunta": "Qual agente tem o poder de invocar um lobo rastreador e feitiços baseados em natureza e caça?", "opcoes": ["Skye", "Sova", "Fade", "Breach"], "resposta": 0},

    # Preenchendo até passar de 150 com variações lógicas e técnicas
    {"pergunta": "Qual o nome da pistola inicial gratuita de 0 créditos?", "opcoes": ["Classic", "Shorty", "Ghost", "Sheriff"], "resposta": 0},
    {"pergunta": "Quantos tiros com a Classic são disparados no modo de tiro secundário (clique direito)?", "opcoes": ["3 tiros em rajada curta", "1 tiro pesado", "5 tiros em leque", "2 tiros rápidos"], "resposta": 0},
    {"pergunta": "Qual o dano base de um tiro na cabeça com a Vandal a curta distância sem armadura?", "opcoes": ["160", "150", "140", "120"], "resposta": 1},
    {"pergunta": "Qual o dano base de um tiro na cabeça com a Phantom a curta distância sem armadura?", "opcoes": ["156", "140", "160", "125"], "resposta": 0},
    {"pergunta": "A Phantom sofre de redução de dano (drop-off) a partir de qual distância?", "opcoes": ["15 metros", "30 metros", "50 metros", "Ela não tem dano reduzido"], "resposta": 0},
    {"pergunta": "A Vandal sofre de redução de dano por distância?", "opcoes": ["Não, o dano na cabeça é sempre o mesmo independente da distância", "Sim, a partir de 10 metros", "Sim, a partir de 25 metros", "Sim, apenas na parede"], "resposta": 0},
    {"pergunta": "Qual o peso de movimento (penalidade de velocidade) ao equipar uma faca comparado a uma arma pesada como a Odin?", "opcoes": ["A faca deixa o personagem mais rápido", "A Odin deixa o personagem mais rápido", "Ambas deixam com a mesma velocidade", "A faca desacelera o personagem"], "resposta": 0},
    {"pergunta": "O que acontece se você disparar enquanto pula sem parar (jump-shooting) com armas de precisão ou rifles na maioria das vezes?", "opcoes": ["A precisão cai drasticamente", "O tiro sai mais forte", "A arma causa dano crítico", "Nada muda"], "resposta": 0},
    {"pergunta": "Qual o nome da mecânica onde o jogador para totalmente o movimento por um microssegundo antes de atirar para garantir precisão?", "opcoes": ["Counter-strafing / Parada seca", "Bunny hop", "Recoil reset", "Spray transfer"], "resposta": 0},
    {"pergunta": "O que significa 'Spray Transfer' no Valorant?", "opcoes": ["Mudar a rajada de tiros de um inimigo para outro mantendo o controle", "Trocar de arma rapidamente", "Comprar armas para o aliado", "Recarregar atrás da parede"], "resposta": 0},

    # Continuamos iterando perguntas de aprofundamento técnico e lore
    {"pergunta": "Qual agente possui um drone de reconhecimento voador que pode marcar inimigos com dardo?", "opcoes": ["Sova", "Cypher", "Fade", "KAY/O"], "resposta": 0},
    {"pergunta": "Qual agente utiliza uma câmera espia que dispara dardos de rastreamento de tinta?", "opcoes": ["Cypher", "Sova", "Killjoy", "Chamber"], "resposta": 0},
    {"pergunta": "Qual o nome da habilidade ultimate da Sage que revive um aliado?", "opcoes": ["Ressurreição", "Cura Suprema", "Orbe Vital", "Imortalidade"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Brimstone?", "opcoes": ["Ataque Orbital", "Chuva de Fogo", "Míssil Tático", "Bombardeio Satelital"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Sova?", "opcoes": ["Fúria do Caçador", "Flecha Suprema", "Tiro Certeiro", "Olho de Águia"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Jett?", "opcoes": ["Tormenta de Aço", "Lâminas da Morte", "Fúria Cortante", "Tempestade de Gelo"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Phoenix?", "opcoes": ["Renascimento", "Fênix Dourada", "Cinzas", "Chama Eterna"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate da Viper?", "opcoes": ["Poço Vipers / Pit", "Nuvem Tóxica Suprema", "Ácido Global", "Névoa Letal"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Omen?", "opcoes": ["Salto das Shadows / From the Shadows", "Teleporte Global", "Visão Sombria", "Aparição"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Cypher?", "opcoes": ["Roubo Neural", "Espionagem Suprema", "Câmera Mestra", "Confissão"], "resposta": 0},

    {"pergunta": "Qual o nome da ultimate da Raze?", "opcoes": ["Sua Hora chegou / Showstopper", "Lança-Foguetes", "Granada Master", "TN-T Power"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate da Reyna?", "opcoes": ["Imperatriz", "Rainha das Sombras", "Fúria Espiritual", "Devoração Total"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Breach?", "opcoes": ["Onda Sísmica / Seismic Shock", "Terremoto", "Fenda Tectônica", "Tremor"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Killjoy?", "opcoes": ["Confinamento / Lockdown", "Bloqueio Total", "Rede de Contenção", "Torre Mestra"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate da Skye?", "opcoes": ["Rastreadores", "Cães Selvagens", "Busca e Destruição", "Matilha"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do KAY/O?", "opcoes": ["NULL/cmd", "Anular", "Hackeamento Global", "Reinicialização"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate da Astra?", "opcoes": ["Divisão Cósmica", "Universo Paralelo", "Barreira Estelar", "Colapso"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Chamber?", "opcoes": ["Tour de Force", "Sniper de Ouro", "Execução", "Tiro Fatal"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate da Neon?", "opcoes": ["Sobrecarga", "Raio Eletrizante", "Velocidade Máxima", "Energia Pura"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate da Fade?", "opcoes": ["Véu da Noite / Nightfall", "Pesadelo", "Medo Profundo", "Escuridão Total"], "resposta": 0},

    {"pergunta": "Qual o nome da ultimate do Gekko?", "opcoes": ["Thrash / Alucinógena", "Poder Máximo", "Ataque dos bichinhos", "Monstro Final"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate da Deadlock?", "opcoes": ["Aniquilação", "Casulo de Contenção", "Rede de Aço", "Paralisia Total"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Iso?", "opcoes": ["Contrato / Kill Contract", "Duelo Mortal", "Arena Fechada", "Zona de Risco"], "resposta": 0},
    {"pergunta": "Qual o nome da ultimate do Clove?", "opcoes": ["Imortais / Not Dead Yet", "Ressurreição Instântanea", "Volta por Cima", "Alma Penada"], "resposta": 0},
    {"pergunta": "Qual o nome da habilidade de granada de concussão do Breach?", "opcoes": ["Ponto de Ignição", "Estouro Retumbante", "Tremor", "Carga Explosiva"], "resposta": 0},
    {"pergunta": "Qual agente possui um robô que rastreia inimigos e explode ao alcançá-los ('Bumba')?", "opcoes": ["Raze", "Killjoy", "Raze e Killjoy", "Nenhum"], "resposta": 0},
    {"pergunta": "Qual agente possui cargas de satchel que permitem saltos explosivos de alta mobilidade?", "opcoes": ["Raze", "Jett", "Neon", "Omen"], "resposta": 0},
    {"pergunta": "Qual o nome da granada de eco do Sova que revela posições por pulsos de sonar?", "opcoes": ["Flecha de Reconhecimento", "Sensor Sonoro", "Pulso Eletromagnético", "Dardo Localizador"], "resposta": 0},
    {"pergunta": "Qual agente possui uma habilidade de adaga congelante que desacelera os inimigos?", "opcoes": ["Fade", "Deadlock", "Sage", "Jett"], "resposta": 1},
    {"pergunta": "Qual agente cria uma cúpula redonda de fumaça escura que abafa sons ao redor?", "opcoes": ["Omen", "Brimstone", "Viper", "Astra"], "resposta": 0},

    {"pergunta": "Qual o nome do criador companheiro verde do Gekko que desarma ou planta a Spike à distância?", "opcoes": ["Wingman", "Dizzy", "Thrash", "Mosh"], "resposta": 0},
    {"pergunta": "Qual criatura do Gekko dispara raios de plasma para cegar os oponentes?", "opcoes": ["Dizzy", "Wingman", "Mosh", "Thrash"], "resposta": 0},
    {"pergunta": "Qual criatura do Gekko funciona como uma granada de dispersão de área que limpa cantos?", "opcoes": ["Mosh Pit", "Wingman", "Dizzy", "Trash"], "resposta": 0},
    {"pergunta": "Qual agente possui uma habilidade de orbe flutuante que drena a vida dos inimigos em área (Orb de Bio-dreno)?", "opcoes": ["Reyna", "Sage", "Viper", "Astra"], "resposta": 0},
    {"pergunta": "Qual agente pode planar no ar segurando a tecla de pulso?", "opcoes": ["Jett", "Phoenix", "Omen", "Reyna"], "resposta": 0},
    {"pergunta": "Qual o nome do mapa tático com três locais de plantio e um design de rotas complexas baseado na Índia?", "opcoes": ["Lotus", "Ascent", "Bind", "Breeze"], "resposta": 0},
    {"pergunta": "Qual o nome da agência ou empresa mal-intencionada que controla grande parte da tecnologia de Radianita na lore?", "opcoes": ["Kingdom Corporation", "Apex", "Radianite Inc", "Omega Group"], "resposta": 0},
    {"pergunta": "Quantos jogadores compõem uma partida padrão de ranqueada em cada lado (Atacantes vs Defensores)?", "opcoes": ["5 contra 5", "3 contra 3", "4 contra 4", "6 contra 6"], "resposta": 0},
    {"pergunta": "O que acontece se uma partida competitiva terminar empatada em 12 a 12?", "opcoes": ["Inicia-se a prorrogação (Overtime) por vantagem de 2 rounds", "O jogo acaba em empate definitivo", "Quem tiver mais dinheiro vence", "Há uma disputa de pênaltis de faca"], "resposta": 0},
    {"pergunta": "Como funciona o sistema de vitória na prorrogação do Valorant competitivo?", "opcoes": ["Vence quem abrir 2 rodadas de vantagem primeiro", "Vence quem fizer o primeiro ponto", "Joga-se apenas mais 1 rodada", "O jogo vai para o sorteio"], "resposta": 0}
]